CREATE PROC FI_SP_ConsBeneficiario	
@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT CPF, NOME, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT CPF, NOME, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID
END